### ISSUE TITLE
Create a service instance and service binding

### ISSUE THREAD

**Issue by serkan4545** [SAP-samples/btp-hyperscaler-extension#2]
Hello,

I am trying to follow the tutorial and I at the part: 
Create a service instance and service binding more specifically at step 
5. Apply the resource file in your cluster to create the instance.

I get the following errors:
`"https://raw.githubusercontent.com/SAP-samples/btp-hyperscaler-extension/master/k8s/createservice.yaml" cannot be recognized: no matches for type "ServiceInstance" in version "services.cloud.sap.com/v1alpha1".
https://raw.githubusercontent.com/SAP-samples/btp-hyperscaler-extension/master/k8s/createservice.yaml" cannot be detected: no matches for type "ServiceBinding" in version "services.cloud.sap.com/v1alpha1".`

What can be the reason for this, for this I have to mention that I have hardly any Kubernetes experience.

Thanks a lot

**Comment by LalithManokar** [comment]
Hi @serkan4545 ,
Thanks for trying out. This Extension relies on SAP-BTP Service operator to create the service instances.
You have to install [SAP-BTP operator](https://github.com/SAP/sap-btp-service-operator)

check this step:
https://developers.sap.com/tutorials/btp-hyperscaler-extension.html#8cac1e86-de09-4071-98c9-b67ec6ef088d
check sap-btp-operator is install successfully.
kubectl get pods -n sap-btp-operator

Regards,
Lalith. S

**Comment by serkan4545** [comment]
Hi @LalithManokar,

thanks for your advice! This workded. But now I have an issue in the Build and Deploy the application into Kubernetes Cluster Step.

I have configured the deployment.yaml file but I'm getting the following problem:

```
NAME                        READY   STATUS             RESTARTS   AGE
fioriapp-58bff8f5d7-dpl4s   0/1     InvalidImageName   0          99m
```

Do you have any idea?

Best regards

**Comment by LalithManokar** [comment]
HI @serkan4545 ,

Problem is due to the proper docker image setup.
please recheck the steps and changes you have made in the deployment.yaml file
https://developers.sap.com/tutorials/btp-hyperscaler-extension.html#4ea2cb6e-6c72-444a-baba-e843d901e040

Regards,
Lalith. S

**Comment by serkan4545** [comment]
Thanks @LalithManokar 
I think this can be closed.

Best regards
Serkan
